name: Dev Lambda Deploy

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  deploy-lambda:
    name: Push zip to S3 and Deploy CloudFront Distribution
    uses: mitlibraries/.github/.github/workflows/cf-lambda-shared-deploy.yml@cf-lambda-publish
    secrets: inherit
    with:
      AWS_REGION: us-east-1
      GHA_ROLE: ledge-custom-domain-gha-dev
      ENVIRONMENT: dev
      UPLOAD_ZIP: true
      ZIP_FILE_NAME: cf-lambda-custom-domain
      TF_WORKSPACE: libraries-website-dev
      TF_AUTO_APPLY: true
