### This is the Terraform-generated GitHub Actions workflow for cf-lambda    ###
### applications for dev/stage/prod. It will publish the Lambda zip to S3    ###
### and automatically re-apply Terraform in the Terraform Cloud              ###
### workloads-libraries-website-prod workspace.                              ###
name: Prod CF Lambda@Edge Full Deploy

on:
  workflow_dispatch: 
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  deploy-lambda:
    if: github.ref == 'refs/heads/main'
    name: Push zip to S3 and Deploy CloudFront Distribution
    uses: mitlibraries/.github/.github/workflows/cf-lambda-shared-deploy.yml@main
    secrets: inherit
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: prod
      GHA_ROLE: ledge-custom-domain-gha-prod
      TF_AUTO_APPLY: false
      TF_WORKSPACE: workloads-libraries-website-prod
      UPLOAD_ZIP: true
