### This is the Terraform-generated GitHub Actions workflow for cf-lambda    ###
### applications for dev/stage/prod. It will publish the Lambda zip to S3    ###
### and optionally re-apply Terraform in the Terraform Cloud                 ###
### workloads-libraries-website-stage workspace.                             ###
name: Stage CF Lambda@Edge Full Deploy

on:
  workflow_dispatch:
  ## We are skipping automation for now  
  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - ".github/**"
  #     - "tests/**"

defaults:
  run:
    shell: bash

jobs:
  deploy-lambda:
    name: Push zip to S3 and Deploy CloudFront Distribution
    uses: mitlibraries/.github/.github/workflows/cf-lambda-shared-deploy.yml@main
    secrets: inherit
    with:
      AWS_REGION: us-east-1
      ENVIRONMENT: stage
      GHA_ROLE: ledge-custom-domain-gha-stage
      TF_AUTO_APPLY: true
      TF_WORKSPACE: workloads-libraries-website-stage
      UPLOAD_ZIP: true
